Android: follow up on instrumentation tests.
Follow up from:
http://codereview.chromium.org/10826071/
Build and install content shell on all attached devices.

BUG=139365
TEST=Android FYI tester runs instrumentation tests.


Review URL: https://chromiumcodereview.appspot.com/10825100

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@149186 0039d316-1c4b-4281-b951-d872f2087c98

diff --git a/build/android/adb_install_content_shell b/build/android/adb_install_content_shell
--- a/build/android/adb_install_content_shell
+++ b/build/android/adb_install_content_shell
@@ -5,6 +5,23 @@ FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-# install -r doesn't always work?  Try uninstalling first.
-adb uninstall org.chromium.content_shell
-adb install -r ${CHROME_SRC}/out/Release/content_shell/ContentShell-debug.apk 
+CONTENT_SHELL_APK=${CHROME_SRC}/out/Release/content_shell/ContentShell-debug.apk
+
+if [ ! -f "${CONTENT_SHELL_APK}" ]; then
+  echo "Error: Could not find ${CONTENT_SHELL_APK} to install."
+  exit 1
+fi
+
+DEVS=$(adb devices | grep device | grep -v devices | awk '{ print $1 }')
+
+if [[ -z $DEVS ]]; then
+  echo "Error: No connected devices. Device needed to run content shell test."
+  exit 1
+fi
+
+for DEV in ${DEVS}; do
+  # Reinstall content shell.  This will also kill existing content_shell procs.
+  echo "Installing ${CONTENT_SHELL_APK} in ${DEV}"
+  adb -s ${DEV} uninstall org.chromium.content_shell
+  adb -s ${DEV} install -r ${CONTENT_SHELL_APK}
+done
